-- MySQL Script generated by MySQL Workbench
-- Mon Nov 17 12:28:05 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema monannonce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monannonce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monannonce` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `monannonce` ;

-- -----------------------------------------------------
-- Table `monannonce`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `cp` VARCHAR(255) NULL,
  `ville` VARCHAR(255) NULL,
  `is_newsletter` TINYINT(1) NOT NULL DEFAULT 1,
  `is_desactiver` TINYINT(1) NOT NULL DEFAULT 0,
  `created` DATETIME NULL,
  `update` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`annonce_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`annonce_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`annonce` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `annonce_type_id` INT NOT NULL,
  `titre` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `nbr_place` INT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `is_refuser` TINYINT(1) NOT NULL DEFAULT 0,
  `adresse` VARCHAR(255) NULL,
  `ville` VARCHAR(255) NULL,
  `cp` VARCHAR(255) NULL,
  `date_debut` DATETIME NULL,
  `date_fin` DATETIME NULL,
  `updated` DATETIME NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_annonce_user_idx` (`user_id` ASC),
  INDEX `fk_annonce_annonce_type1_idx` (`annonce_type_id` ASC),
  CONSTRAINT `fk_annonce_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `monannonce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonce_annonce_type1`
    FOREIGN KEY (`annonce_type_id`)
    REFERENCES `monannonce`.`annonce_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`message_annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`message_annonce` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `annonce_id` INT NOT NULL,
  `message` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discussion_message_user1_idx` (`user_id` ASC),
  INDEX `fk_discussion_message_annonce1_idx` (`annonce_id` ASC),
  CONSTRAINT `fk_discussion_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `monannonce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discussion_message_annonce1`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `monannonce`.`annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`annonce_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`annonce_photo` (
  `id` INT NOT NULL,
  `annonce_id` INT NOT NULL,
  `file_photo` VARCHAR(255) NULL,
  `is_principal` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_annonce_photo_annonce1_idx` (`annonce_id` ASC),
  CONSTRAINT `fk_annonce_photo_annonce1`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `monannonce`.`annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_role_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_user_role_has_user_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role_has_user_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `monannonce`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `monannonce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`message_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`message_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `user_destinataire_id` INT NOT NULL,
  `message` TEXT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discussion_user_user1_idx` (`user_id` ASC),
  INDEX `fk_discussion_user_user2_idx` (`user_destinataire_id` ASC),
  CONSTRAINT `fk_discussion_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `monannonce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discussion_user_user2`
    FOREIGN KEY (`user_destinataire_id`)
    REFERENCES `monannonce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`annonce_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`annonce_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `annonce_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `nbr_personne` INT NULL,
  `note` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_annonce_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_annonce_has_user_annonce1_idx` (`annonce_id` ASC),
  CONSTRAINT `fk_annonce_has_user_annonce1`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `monannonce`.`annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonce_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `monannonce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`departement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL,
  `nom` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monannonce`.`user_departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monannonce`.`user_departement` (
  `departement_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`departement_id`, `user_id`),
  INDEX `fk_departement_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_departement_has_user_departement1_idx` (`departement_id` ASC),
  CONSTRAINT `fk_departement_has_user_departement1`
    FOREIGN KEY (`departement_id`)
    REFERENCES `monannonce`.`departement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departement_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `monannonce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
