bo_annonce:
    resource: "@BoAnnonceBundle/Controller/"
    type:     annotation
    prefix:   /

bo_admin:
    resource: "@BoAdminBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

